script:
  - id: on_${climate_entity}_hvac_mode_${hvac_mode}_activated
    mode: queued
    then:
      - lvgl.widget.update:
          id: btn_${climate_entity}_${hvac_mode}_mode
          state:
            checked: true