# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

##############################
## My custom configurations ##
##############################

# HTTP settings
http:
  # NGINX SSL proxy settings: https://github.com/home-assistant/addons/blob/master/nginx_proxy/DOCS.md#how-to-use
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

    # Additional IP filtering using log in attempt threshold
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Logbook customization
logbook:
  exclude:
    entities:
      - sensor.date_time_iso

# Command line integrations
command_line:
  - sensor:
      name: dani-home.tplinkdns.com
      command: "sh -euc 'cd ./openssl && chmod u+x ./print_certificate_expiration_date.sh && ./print_certificate_expiration_date.sh'"
      command_timeout: 30 # in secs
      scan_interval: 3600 # 1 hour in secs
      icon: mdi:certificate
      device_class: timestamp

# Custom sensor
sensor:
  - platform: time_date
    display_options:
      - "date_time_iso"

# Notification settings
notify:
  - platform: group
    name: "Mobile app notifications"
    services:
      # Dani mobile phone
      - service: mobile_app_dani_s10
      # Timi mobile phone
      - service: mobile_app_timi_iphone_13
      # Home tablet
      - service: mobile_app_dani_home_tablet
# Custom alerting
alert:
  garage_door:
    name: Garage is opened
    message: Garage door is opened!
    done_message: clear_notification
    entity_id: binary_sensor.pico_w_1_garage_door_opening
    state: "on"
    repeat: # in minutes
      - 15
      - 30
      - 60
    can_acknowledge: false
    skip_first: true
    data:
      tag: alerts.garage_door_is_opened
      actions:
        - action: "notification.actions.move_garage_door"
          title: "Move"
        - action: "notification.actions.snooze_garage_door_is_opened"
          title: "Snooze"
    notifiers:
      - mobile_app_notifications

  sliding_gate:
    name: Sliding gate is opened
    message: Sliding gate is opened!
    done_message: clear_notification
    entity_id: binary_sensor.pico_w_1_sliding_gate_opening
    state: "on"
    repeat: # in minutes
      - 15
      - 30
      - 60
    can_acknowledge: false
    skip_first: true
    data:
      tag: alerts.sliding_gate_is_opened
      actions:
        - action: "notification.actions.move_sliding_gate"
          title: "Move"
        - action: "notification.actions.snooze_sliding_gate_is_opened"
          title: "Snooze"
    notifiers:
      - mobile_app_notifications
