# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# -----------------------------------------------------------------------
# HTTP Integration Settings
# -----------------------------------------------------------------------
http:
  # NGINX SSL proxy settings: https://github.com/home-assistant/addons/blob/master/nginx_proxy/DOCS.md#how-to-use
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

    # Additional IP filtering using log in attempt threshold
  ip_ban_enabled: true
  login_attempts_threshold: 5

# -----------------------------------------------------------------------
# Logbook Customization
# -----------------------------------------------------------------------
logbook:
  exclude:
    entities:
      - sensor.date_time_iso

# -----------------------------------------------------------------------
# ZHA Integration
# -----------------------------------------------------------------------
zha:
  device_config:
    a4:c1:38:b7:91:31:44:ad-1:
      type: "switch"

# -----------------------------------------------------------------------
# Command Line Integration
# -----------------------------------------------------------------------
command_line:
  - sensor:
      name: !secret my_domain
      command: "sh -euc 'cd ./openssl && chmod u+x ./print_certificate_expiration_date.sh && ./print_certificate_expiration_date.sh'"
      command_timeout: 30 # in secs
      scan_interval: 3600 # 1 hour in secs
      icon: mdi:certificate
      device_class: timestamp
  - sensor:
      name: "Disk temperature"
      command: "cat /sys/class/nvme/nvme0/hwmon1/temp1_input"
      command_timeout: 1
      scan_interval: 5
      value_template: "{{ value | int | multiply(0.001) | round(1) }}"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement

# -----------------------------------------------------------------------
# Custom Sensors
# -----------------------------------------------------------------------
sensor:
  - platform: time_date
    display_options:
      - "date_time_iso"

# -----------------------------------------------------------------------
# Generec thermostat for heating control
# -----------------------------------------------------------------------
climate:
  - platform: generic_thermostat
    unique_id: b14cbe92d4cc4d56b8e09427f751a69f
    name: Gas boiler thermostat
    ac_mode: false
    heater: switch.gas_boiler_switch
    target_sensor: sensor.livingroom_temp_sensor_temperature
    min_temp: 18
    max_temp: 25
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    precision: 0.1
    target_temp_step: 0.1
    keep_alive:
      seconds: 30

# -----------------------------------------------------------------------
# Notification Settings
# -----------------------------------------------------------------------
notify:
  - platform: group
    name: "Mobile app notifications"
    services:
      # Dani mobile phone
      - service: mobile_app_sm_s911b
      # Timi mobile phone
      - service: mobile_app_timi_iphone_13
      # Home tablet
      - service: mobile_app_dani_home_tablet

# -----------------------------------------------------------------------
# Alerting
# -----------------------------------------------------------------------
alert:
  garage_door:
    name: Garage is opened
    message: Garage door is opened!
    done_message: clear_notification
    entity_id: binary_sensor.pico_w_1_garage_door_opening
    state: "on"
    repeat: # in minutes
      - 15
      - 30
      - 60
    can_acknowledge: false
    skip_first: true
    data:
      tag: alerts.garage_door_is_opened
    notifiers:
      - mobile_app_notifications

  sliding_gate:
    name: Sliding gate is opened
    message: Sliding gate is opened!
    done_message: clear_notification
    entity_id: binary_sensor.pico_w_1_sliding_gate_opening
    state: "on"
    repeat: # in minutes
      - 15
      - 30
      - 60
    can_acknowledge: false
    skip_first: true
    data:
      tag: alerts.sliding_gate_is_opened
    notifiers:
      - mobile_app_notifications
