# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# -----------------------------------------------------------------------
# HTTP Integration Settings
# -----------------------------------------------------------------------
http:
  # NGINX SSL proxy settings: https://github.com/home-assistant/addons/blob/master/nginx_proxy/DOCS.md#how-to-use
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

    # Additional IP filtering using log in attempt threshold
  ip_ban_enabled: true
  login_attempts_threshold: 5

# -----------------------------------------------------------------------
# Logbook Customization
# -----------------------------------------------------------------------
logbook:
  exclude:
    entities:
      - sensor.date_time_iso

# -----------------------------------------------------------------------
# ZHA Integration
# -----------------------------------------------------------------------
zha:
  device_config:
    a4:c1:38:b7:91:31:44:ad-1: # gas boiler tuya zigbee relay
      type: "switch"

# -----------------------------------------------------------------------
# Command Line Integration
# -----------------------------------------------------------------------
command_line:
  - sensor:
      name: "Disk temperature"
      command: "cat /sys/class/nvme/nvme0/hwmon1/temp1_input"
      command_timeout: 1
      scan_interval: 5
      value_template: "{{ value | int | multiply(0.001) | round(1) }}"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement

# -----------------------------------------------------------------------
# Custom Sensors
# -----------------------------------------------------------------------
sensor:
  - platform: time_date
    display_options:
      - "date_time_iso"

# -----------------------------------------------------------------------
# Generec thermostat for heating control
# -----------------------------------------------------------------------
climate:
  - platform: generic_thermostat
    unique_id: b14cbe92d4cc4d56b8e09427f751a69f
    name: Gas boiler thermostat
    ac_mode: false
    heater: switch.gas_boiler_switch
    target_sensor: sensor.livingroom_temp_sensor_temperature
    min_temp: 18
    max_temp: 25
    cold_tolerance: 0.0
    hot_tolerance: 0.1
    precision: 0.1
    target_temp_step: 0.1
    keep_alive:
      seconds: 30

# -----------------------------------------------------------------------
# Template cover for terrace awning
# -----------------------------------------------------------------------
cover:
  - platform: template
    covers:
      awning:
        friendly_name: "Awning"
        icon_template: mdi:awning-outline
        open_cover:
          action: switch.turn_on
          target:
            entity_id: switch.sonoff_1002324a8a_2
        close_cover:
          action: switch.turn_on
          target:
            entity_id: switch.sonoff_1002324a8a_1
        stop_cover:
          action: switch.turn_off
          target:
            entity_id:
              - switch.sonoff_1002324a8a_2
              - switch.sonoff_1002324a8a_1
        availability_template: |-
          {{ states("switch.sonoff_1002324a8a_2") != "unavailable" and states("switch.sonoff_1002324a8a_1") != "unavailable" }}
        value_template: |-
          {% if is_state('binary_sensor.awning_closed_sensor', 'off') %}
            closed
          {% elif is_state('binary_sensor.awning_open_sensor', 'off') %}
            open
          {% elif is_state('switch.sonoff_1002324a8a_2', 'on') %}
            opening
          {% elif is_state('switch.sonoff_1002324a8a_1', 'on') %}
            closing
          {% else %}
            {% if this.state in ['opening', 'closing'] %}
              open
            {% else %}
              {{ this.state }}
            {% endif %}
          {% endif %}

# -----------------------------------------------------------------------
# Notification Settings
# -----------------------------------------------------------------------
notify:
  - platform: group
    name: "Garage door and gate alerting group"
    services:
      # Dani mobile phone
      - service: mobile_app_sm_s911b
      # Timi mobile phone
      - service: mobile_app_timi_iphone_13
      # Home tablet
      - service: mobile_app_dani_home_tablet

# -----------------------------------------------------------------------
# Alerting
# -----------------------------------------------------------------------
alert:
  garage_door:
    name: Garage is opened
    message: Garage door is opened!
    done_message: clear_notification
    entity_id: binary_sensor.pico_w_1_garage_door_opening
    state: "on"
    repeat: # in minutes
      - 15
      - 30
      - 60
    can_acknowledge: false
    skip_first: true
    data:
      tag: alerts.garage_door_is_opened
    notifiers:
      - garage_door_and_gate_alerting_group

  sliding_gate:
    name: Sliding gate is opened
    message: Sliding gate is opened!
    done_message: clear_notification
    entity_id: binary_sensor.pico_w_1_sliding_gate_opening
    state: "on"
    repeat: # in minutes
      - 15
      - 30
      - 60
    can_acknowledge: false
    skip_first: true
    data:
      tag: alerts.sliding_gate_is_opened
    notifiers:
      - garage_door_and_gate_alerting_group
