packages:
  climate-sensors: !include climate-sensors.yaml
  climate-hvac-scripts: !include climate-hvac-change-sripts.yaml

lvgl:
  pages:    
    - id: climate_${climate_entity}_page
      on_load:
        then:
          script.execute:
            id: lvgl_sub_page_loaded
            page_title: "${climate_page_title}"
      styles: page_base
      layout:
        type: grid
        grid_rows: [fr(1), content, fr(1)]
        grid_columns: [fr(1), content, fr(1)]
        pad_column: 0
        pad_row: 0
      widgets:
        - arc:
            id: "arc_${climate_entity}_hvac_action"
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_row_span: 3
            grid_cell_column_span: 3
            grid_cell_x_align: center
            grid_cell_y_align: center
            adjustable: false
            value: 100
            width: 335
            height: 335
            arc_width: 3
            indicator:
              arc_color: color_dark_card
              arc_opa: cover
              arc_width: 3
        - label:
            id: "lbl_${climate_entity}_hvac_action"
            grid_cell_row_pos: 0
            grid_cell_column_pos: 1
            grid_cell_x_align: center
            grid_cell_y_align: end
            text: "-"
            styles: climate_secondary_info_label
        - label:
            id: "lbl_${climate_entity}_current_temp"
            grid_cell_row_pos: 2
            grid_cell_column_pos: 1
            grid_cell_x_align: center
            grid_cell_y_align: start
            text: "--.- °C"
            styles: climate_secondary_info_label
        - button:
            id: "btn_increase_${climate_entity}_target_temp"
            grid_cell_row_pos: 1
            grid_cell_column_pos: 2
            grid_cell_x_align: end
            grid_cell_y_align: center
            styles: climate_target_temp_button
            widgets:
              - label:
                  text: "+"
                  styles: climate_target_temp_button_label
            on_click:
              then:
                homeassistant.action:
                  action: "climate.set_temperature"
                  data:
                    entity_id: "climate.${climate_entity}"
                    temperature: !lambda
                      return id(ha_${climate_entity}_target_temp_sensor).state +
                        id(ha_${climate_entity}_target_temp_step_sensor).state;
        - button:
            id: "btn_decrease_${climate_entity}_target_temp"
            grid_cell_row_pos: 1
            grid_cell_column_pos: 0
            grid_cell_x_align: start
            grid_cell_y_align: center
            styles: climate_target_temp_button
            widgets:
              - label:
                  text: "-"
                  styles: climate_target_temp_button_label
            on_click:
              then:
                homeassistant.action:
                  action: "climate.set_temperature"
                  data:
                    entity_id: "climate.${climate_entity}"
                    temperature: !lambda
                      return id(ha_${climate_entity}_target_temp_sensor).state -
                        id(ha_${climate_entity}_target_temp_step_sensor).state;
        - label:
            id: "lbl_${climate_entity}_target_temp"
            grid_cell_row_pos: 1
            grid_cell_column_pos: 1
            grid_cell_x_align: center
            grid_cell_y_align: center
            text: "--.-"
            text_font: "roboto_96"
            pad_top: 10
            pad_bottom: 10
            pad_left: 0
            pad_right: 0
        - label:
            id: "lbl_${climate_entity}_target_temp_unit"
            grid_cell_row_pos: 1
            grid_cell_column_pos: 2
            text: "°C"
            text_font: "roboto_28"
            pad_top: 26
        - obj:
            grid_cell_row_pos: 2
            grid_cell_column_span: 3
            grid_cell_column_pos: 0
            grid_cell_x_align: center
            grid_cell_y_align: end
            styles: climate_hvac_mode_buttons
            scrollable: false
            layout:
              type: flex
              flex_flow: row
              flex_align_main: center
              flex_align_cross: center
              flex_align_track: center
            widgets:
              - button:
                  id: btn_${climate_entity}_cool_mode
                  styles: climate_hvac_mode_button
                  hidden: !lambda return !str_equals_case_insensitive("${supports_cool_mode}", "True");
                  widgets:
                    - label:
                        align: center
                        text: "\U000F0717"
                  on_click:
                    then:
                      homeassistant.action:
                        action: "climate.set_hvac_mode"
                        data:
                          entity_id: "climate.${climate_entity}"
                          hvac_mode: "cool"
              - button:
                  id: btn_${climate_entity}_heat_mode
                  styles: climate_hvac_mode_button
                  hidden: !lambda return !str_equals_case_insensitive("${supports_heat_mode}", "True");
                  widgets:
                    - label:
                        align: center
                        text: "\U000F0238"
                  on_click:
                    then:
                      homeassistant.action:
                        action: "climate.set_hvac_mode"
                        data:
                          entity_id: "climate.${climate_entity}"
                          hvac_mode: "heat"
              - button:
                  id: btn_${climate_entity}_off_mode
                  styles: climate_hvac_mode_button
                  widgets:
                    - label:
                        align: center
                        text: "\U000F0906"
                  on_click:
                    homeassistant.action:
                      action: "climate.set_hvac_mode"
                      data:
                        entity_id: "climate.${climate_entity}"
                        hvac_mode: "off"