lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  default_font: "roboto_14"
  on_idle:
    timeout: ${lvgl_idle_timeout}
    then:
      - if:
          condition:
            lambda: |-
              return id(ha_gas_boiler_hvac_action_sensor).state != "Heating";
          then:
            - script.execute: lvgl_pause
  style_definitions:
    - id: header_label
      text_font: "roboto_24"
      text_color: color_light_blue_main
      text_align: center
      height: 50
    - id: target_temp_button
      height: 50
      width: 50
      bg_color: color_dark_card
    - id: target_temp_button_label
      text_font: "roboto_26"
      align: center
    - id: hvac_toggle_button_matrix
      height: 50
      width: 340
      pad_column: 0
      pad_all: 0
      border_width: 0
    - id: hvac_toggle_button
      text_font: "roboto_26"
      bg_opa: transp
    - id: secondary_info_label
      text_font: roboto_32
  top_layer:
    scrollable: false
    widgets:
      - label:
          id: lbl_time
          align: top_left
          styles: header_label
          text: "--:--"
      - obj:
          id: "connections_container"
          border_width: 0
          height: 50
          bg_opa: transp
          pad_all: 0
          align: top_right
          layout:
            type: flex
            flex_flow: row
            pad_row: 0
            flex_align_main: end
            flex_align_cross: center
            flex_align_track: center
          widgets:
            - label:
                id: "lbl_api_connection"
                hidden: true
                text: "\U000F07D0"
                styles: header_label
            - label:
                id: "lbl_wifi_connection"
                hidden: true
                text: "\U000F05A9"
                styles: header_label
  pages:
    - id: main_page
      on_load:
        then:
          lambda: |-
            lv_theme_t * darkth = lv_theme_default_init(NULL, lv_palette_main(LV_PALETTE_LIGHT_BLUE), lv_palette_main(LV_PALETTE_AMBER), true, lv_theme_get_font_normal(NULL));
            lv_disp_set_theme(NULL, darkth);
            ESP_LOGD("main_page", "Dark theme configured successfully.");
      layout:
        type: grid
        grid_rows: [fr(1), content, fr(1)]
        grid_columns: [fr(1), content, fr(1)]
        pad_column: 0
      widgets:
        - arc:
            id: "arc_hvac_action"
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_row_span: 3
            grid_cell_column_span: 3
            grid_cell_x_align: center
            grid_cell_y_align: center
            adjustable: false
            value: 100
            width: 315
            height: 315
            translate_y: 8
            arc_width: 3
            indicator:
              arc_color: color_heating
              arc_opa: transp
              arc_width: 3
        - label:
            id: "lbl_hvac_action"
            grid_cell_row_pos: 0
            grid_cell_column_pos: 1
            grid_cell_x_align: center
            grid_cell_y_align: end
            text: "-"
            styles: secondary_info_label
            pad_bottom: 8
        - label:
            id: "lbl_current_temp"
            grid_cell_row_pos: 2
            grid_cell_column_pos: 1
            grid_cell_x_align: center
            grid_cell_y_align: start
            text: "--.- °C"
            styles: secondary_info_label
            pad_top: 10
        - button:
            id: "btn_increase_target_temp"
            grid_cell_row_pos: 1
            grid_cell_column_pos: 2
            grid_cell_x_align: end
            grid_cell_y_align: center
            styles: target_temp_button
            widgets:
              - label:
                  text: "+"
                  styles: target_temp_button_label
            on_click:
              then:
                homeassistant.action:
                  action: "climate.set_temperature"
                  data:
                    entity_id: "climate.gas_boiler_thermostat"
                    temperature: !lambda
                      return id(ha_gas_boiler_temp_sensor).state + id(ha_gas_boiler_target_temp_step_sensor).state;
        - button:
            id: "btn_decrease_target_temp"
            grid_cell_row_pos: 1
            grid_cell_column_pos: 0
            grid_cell_x_align: start
            grid_cell_y_align: center
            styles: target_temp_button
            widgets:
              - label:
                  text: "-"
                  styles: target_temp_button_label
            on_click:
              then:
                homeassistant.action:
                  action: "climate.set_temperature"
                  data:
                    entity_id: "climate.gas_boiler_thermostat"
                    temperature: !lambda
                      return id(ha_gas_boiler_temp_sensor).state - id(ha_gas_boiler_target_temp_step_sensor).state;
        - label:
            id: "lbl_target_temp"
            grid_cell_row_pos: 1
            grid_cell_column_pos: 1
            grid_cell_x_align: center
            grid_cell_y_align: center
            text: "--.-"
            text_font: "roboto_96"
            pad_all: 0
        - label:
            id: "lbl_target_temp_unit"
            grid_cell_row_pos: 1
            grid_cell_column_pos: 2
            text: "°C"
            text_font: "roboto_28"
            pad_top: 17
        - buttonmatrix:
            id: "btn_matrix_modes"
            grid_cell_row_pos: 2
            grid_cell_column_span: 3
            grid_cell_column_pos: 0
            grid_cell_x_align: center
            grid_cell_y_align: end
            one_checked: true
            styles: hvac_toggle_button_matrix
            items:
              styles: hvac_toggle_button
            rows:
              - buttons:
                  - text: "\U000F0238"
                    id: btn_heat
                    control:
                      checkable: true
                    on_value:
                      then:
                        - if:
                            condition:
                              lambda: |-
                                return x;
                            then:
                              - homeassistant.action:
                                  action: "climate.set_hvac_mode"
                                  data:
                                    entity_id: "climate.gas_boiler_thermostat"
                                    hvac_mode: "heat"
                  - text: "\U000F0906"
                    id: btn_off
                    control:
                      checkable: true
                    on_value:
                      then:
                        - if:
                            condition:
                              lambda: |-
                                return x;
                            then:
                              - homeassistant.action:
                                  action: "climate.set_hvac_mode"
                                  data:
                                    entity_id: "climate.gas_boiler_thermostat"
                                    hvac_mode: "off"
        - label:
            id: "lbl_title"
            text: "\U000F0393 GAS BOILER"
            styles: header_label
            grid_cell_x_align: center
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_column_span: 3
