packages:
  #-------------------------------
  # ====== DASHBOARD PAGE ======
  #-------------------------------
  lvgl_dashboard_page: !include pages/dashboard/dashboard.yaml
  #-----------------------------
  # ====== CLIMATE PAGES ======
  #-----------------------------
  lvgl_climate_page_styles: !include pages/climate/styles/styles.yaml
  #
  # 1. GAS BOILER PAGE
  #
  lvgl_climate_gas_boiler: !include
    file: pages/climate/climate.yaml
    vars:
      climate_page_title: "\U000F0438 GAS BOILER"
      climate_entity: gas_boiler_thermostat
      supports_cool_mode: false
      supports_heat_mode: true
  #
  # 2. LIVINGROOM AC PAGE
  #
  lvgl_climate_livingroom_ac: !include
    file: pages/climate/climate.yaml
    vars:
      climate_page_title: "\U000F001B LIVINGROOM AC"
      climate_entity: livingroom_panasonic_ac_livingroom_panasonic_ac
      supports_cool_mode: true
      supports_heat_mode: true
  #
  # 3. BEDROOM AC PAGE
  #
  lvgl_climate_bedroom_ac: !include
    file: pages/climate/climate.yaml
    vars:
      climate_page_title: "\U000F001B BEDROOM AC"
      climate_entity: bedroom_panasonic_ac_bedroom_panasonic_ac
      supports_cool_mode: true
      supports_heat_mode: true

lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  default_font: "roboto_14"
  on_idle:
    - timeout: 20s
      then:
        - logger.log: "LVGL has been idle for 20secs: navigating to dashboard page"
        - script.execute: lvgl_show_dashboard_page
    - timeout: ${lvgl_idle_timeout}
      then:
        - logger.log: "LVGL has been idle for ${lvgl_idle_timeout}: turning display off."
        - if:
            condition:
              binary_sensor.is_off: keep_display_on
            then:
              - script.execute: lvgl_pause
  on_resume:
    - script.execute: lvgl_show_dashboard_page
  style_definitions:
    - id: page_base
      pad_top: 45 # 35 height + 5 pad-top + 5 pad-bottom 
      pad_right: 5
      pad_bottom: 5
      pad_left: 5
    - id: header_label
      text_font: "roboto_28"
      text_color: color_light_blue_main
      text_align: center
  top_layer:
    pad_all: 5
    widgets:
      - button:
          id: btn_show_dashboard_page
          bg_opa: transp
          border_width: 0
          radius: 0
          pad_all: 0
          align: top_left
          width: 70
          widgets:
            - label:
                id: lbl_btn_show_dashboard_page
                align: left_mid
                styles: header_label
                text: "\U000F004D"
          on_click:
            then:
              script.execute: lvgl_show_dashboard_page
      - label:
          id: lbl_time
          align: top_left
          styles: header_label
          text: "--:--"
      - label:
          id: lbl_sub_page_title
          align: top_mid
          styles: header_label
          text: ""
      - obj:
          id: "connections_container"
          border_width: 0
          height: 35
          bg_opa: transp
          pad_all: 0
          align: top_right
          scrollable: false
          layout:
            type: flex
            flex_flow: row
            pad_row: 0
            flex_align_main: end
            flex_align_cross: center
            flex_align_track: center
          widgets:
            - label:
                id: "lbl_api_connection"
                hidden: true
                text: "\U000F07D0"
                styles: header_label
            - label:
                id: "lbl_wifi_connection"
                hidden: true
                text: "\U000F05A9"
                styles: header_label