esphome:
  name: bedroom-panasonic-ac
  friendly_name: Bedroom Panasonic AC

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE
  logs:
    api.service: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: e2U03hQHz6Uk/6x20tnmhRJNNb21/N8z7yDvVfR+StY=

ota:
  - platform: esphome
    password: b695133c00a03841f8aeb38d6d615c53

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#############################
## Panasonic AC controller ##
#############################
external_components:
  source: github://dbiro/esphome-panasonic-ac
  components: [panasonic_ac]

uart:
  # For some reason default TX and RX pins not work!
  # See: https://github.com/DomiStyle/esphome-panasonic-ac/issues/119#issuecomment-2199421760
  rx_pin: GPIO18
  tx_pin: GPIO19
  baud_rate: 9600
  parity: EVEN
  stop_bits: 1

climate:
  - platform: panasonic_ac
    name: None # use device's friendly name (https://esphome.io/components/climate/#base-climate-configuration)
    traits:
      vertical_swing_mode:
        supported: true
        selector:
          name: Vertical Swing Mode
      horizontal_swing_mode:
        supported: false
      nanoex_mode:
        supported: false
      outside_temperature:
        supported: true
        sensor:
          name: Outside Temperature
      current_power_consumption:
        supported: false