substitutions:
  esphome_node_name: host-dev-node
  esphome_node_friendly_name: Host Dev Node

packages:
  device_base: !include packages/core/device-base.yaml
  homeassistant: !include packages/lvgl/homeassistant.yaml
  lvgl: !include packages/lvgl/control-panel.yaml
  lvgl_fonts: !include packages/lvgl/fonts.yaml
  lvgl_colors: !include packages/lvgl/colors.yaml
  sdl: !include
    file: packages/hardware/sdl-touchscreen.yaml
    vars:
      sdl_display_width: 480
      sdl_display_height: 480

host:

ota: !remove

logger:
  level: DEBUG

# -----------------------------
# Setup API triggers
# -----------------------------
api:
  on_client_connected:
    then:
      lvgl.widget.show: lbl_api_connection
  on_client_disconnected:
    then:
      - if:
          condition:
            - not: api.connected
          then:
            - lvgl.widget.hide: lbl_api_connection

# -----------------------------
# Setup fake Wi-Fi triggers
# -----------------------------
esphome:
  on_boot:
    then:
      lvgl.widget.show: lbl_wifi_connection
