substitutions:
  esphome_node_name: host-dev-node
  esphome_node_friendly_name: Host Dev Node

packages:
  device_base: !include packages/core/device-base.yaml
  lvgl_fonts: !include packages/lvgl/fonts.yaml
  lvgl_colors: !include packages/lvgl/colors.yaml
  lvgl_homeassistant: !include packages/lvgl/homeassistant.yaml
  lvgl_api: !include packages/lvgl/triggers/api.yaml
  lvgl: !include packages/lvgl/control-panel.yaml
  sdl: !include
    file: packages/hardware/sdl-touchscreen.yaml
    vars:
      sdl_display_width: 480
      sdl_display_height: 480

host:

ota: !remove

logger:
  level: DEBUG

# -----------------------------
# Display Wi-Fi icon without WiFi
# -----------------------------
esphome:
  on_boot:
    then:
      lvgl.widget.show: lbl_wifi_connection
