esphome:
  name: livingroom-panasonic-ac
  friendly_name: Livingroom Panasonic AC

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE
  logs:
    api.service: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret livingroom_panasonic_ac_api_encryption_key

ota:
  - platform: esphome
    password: !secret livingroom_panasonic_ac_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#############################
## Panasonic AC controller ##
#############################
external_components:
  # source: github://dbiro/esphome-panasonic-ac
  source:
    type: local
    path: source/esphome-panasonic-ac/components
  components: [panasonic_ac]

uart:
  # For some reason default TX and RX pins not work!
  # See: https://github.com/DomiStyle/esphome-panasonic-ac/issues/119#issuecomment-2199421760
  rx_pin: GPIO18
  tx_pin: GPIO19  
  baud_rate: 9600
  parity: EVEN
  stop_bits: 1

climate:
  - platform: panasonic_ac
    name: None # use device's friendly name (https://esphome.io/components/climate/#base-climate-configuration)
    traits:
      vertical_swing_mode:
        supported: true
        selector:
          name: Vertical Swing Mode
      horizontal_swing_mode:
        supported: true
        selector:
          name: Horizontal Swing Mode
      nanoex_mode:
        supported: true
        switch:
          name: NanoeX    
      outside_temperature:
        supported: true
        sensor:
          name: Outside Temperature
      current_power_consumption:
        supported: true
        sensor:
          name: Power Consumption
