esphome:
  name: livingroom-panasonic-ac
  friendly_name: Livingroom Panasonic AC

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret livingroom_panasonic_ac_api_encryption_key

ota:
  - platform: esphome
    password: !secret livingroom_panasonic_ac_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#############################
## Panasonic AC controller ##
#############################
external_components:
  # == Released version ==
  # source: github://dbiro/esphome-panasonic-ac@v1.1.0
  # == Local Development ==
  source:
    type: local
    path: source/esphome-panasonic-ac/components
  components: [panasonic_ac]

uart:
  # For some reason default TX and RX pins not work!
  # See: https://github.com/DomiStyle/esphome-panasonic-ac/issues/119#issuecomment-2199421760
  rx_pin: GPIO18
  tx_pin: GPIO19
  baud_rate: 9600
  parity: EVEN
  stop_bits: 1

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: total_daily_energy
    name: Daily Energy Usage
    power_id: current_power_consumption
    unit_of_measurement: "kWh"
    accuracy_decimals: 2

climate:
  - platform: panasonic_ac
    name: None
    traits:
      vertical_swing_mode:
        supported: true
        selector:
          name: Vertical Swing Mode
      horizontal_swing_mode:
        supported: true
        selector:
          name: Horizontal Swing Mode
      nanoex_mode:
        supported: true
        switch:
          name: NanoeX    
      outside_temperature:
        supported: true
        sensor:
          name: Outside Temperature
      current_temperature:
        supported: true
        sensor:
          name: Current Temperature
      current_power_consumption:
        supported: true
        sensor:
          id: current_power_consumption
          name: Power Consumption
          unit_of_measurement: "kW"
          accuracy_decimals: 2
          filters:
            # Multiplication factor from W to kW is 0.001
            - multiply: 0.001