substitutions:
  esphome_node_name: livingroom-panasonic-ac
  esphome_node_friendly_name: Livingroom Panasonic AC

packages:
  device_base: !include packages/core/device-base.yaml
  wifi: !include packages/core/wifi.yaml

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: DEBUG

#############################
## Panasonic AC controller ##
#############################
external_components:
  source: github://dbiro/esphome-panasonic-ac@v1.2.0
  components: [panasonic_ac]

uart:
  # For some reason default TX and RX pins not work!
  # See: https://github.com/DomiStyle/esphome-panasonic-ac/issues/119#issuecomment-2199421760
  rx_pin: GPIO18
  tx_pin: GPIO19
  baud_rate: 9600
  parity: EVEN
  stop_bits: 1

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: total_daily_energy
    name: Daily Energy Usage
    power_id: current_power_consumption
    unit_of_measurement: "kWh"
    accuracy_decimals: 2

climate:
  - platform: panasonic_ac
    name: None
    traits:
      vertical_swing_mode:
        supported: true
        selector:
          name: Vertical Swing Mode
      horizontal_swing_mode:
        supported: true
        selector:
          name: Horizontal Swing Mode
      nanoex_mode:
        supported: true
        switch:
          name: NanoeX    
      outside_temperature:
        supported: true
        sensor:
          name: Outside Temperature
      current_temperature:
        supported: true
        sensor:
          name: Current Temperature
      current_power_consumption:
        supported: true
        sensor:
          id: current_power_consumption
          name: Power Consumption
          unit_of_measurement: "kW"
          accuracy_decimals: 2
          filters:
            # Multiplication factor from W to kW is 0.001
            - multiply: 0.001