esphome:
  name: livingroom-panasonic-ac
  friendly_name: Livingroom Panasonic AC

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE
  logs:
    api.service: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "gN6jqXDu+1aNUXdpzyPJj3GhPTJxsfub7EUbDugYnTE="

ota:
  - platform: esphome
    password: "fa7ad02a06069df588bef31b9d1fee86"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom-Panasonic-Ac"
    password: "V8KR7cKeNGIN"

captive_portal:

#############################
## Panasonic AC controller ##
#############################
uart:
  rx_pin: GPIO18
  tx_pin: GPIO19  
  baud_rate: 9600
  parity: EVEN
  stop_bits: 1

external_components:
  # source: github://dbiro/esphome-panasonic-ac
  source:
    type: local
    path: source/esphome-panasonic-ac/components
  components: [panasonic_ac]

climate:
  - platform: panasonic_ac    
    name: None
    icon: mdi:air-conditioner
    type: cnt
    horizontal_swing_select:
      name: Horizontal Swing Mode
    vertical_swing_select:
      name: Vertical Swing Mode
    nanoex_switch:
      name: NanoeX Switch
    outside_temperature:
      name: Outside Temperature
    current_power_consumption:
      name: AC Power Consumption

    # Other options:
    # eco_switch:
    #  name: Livingroom Panasonic AC Eco Switch
    # mild_dry_switch:
    #   name: Panasonic AC Mild Dry Switch
    # Useful when the ac does not report a current temperature (CZ-TACG1 only)
    # current_temperature_sensor: temperature_sensor_id
