esphome:
  name: pico-w-1
  friendly_name: Pico W 1

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "o7GH7eTZLB9WVn4Y+uc1APScUiJaXaLyBXQ5hwd5XbI="

ota:
  password: "d7523ecc485afb775a8298543b9c8ed1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Pico-W-1 Fallback Hotspot"
    password: "jIsIqVokFA1a"

output:
  - platform: gpio
    pin: 32 # https://randomnerdtutorials.com/raspberry-pi-pico-w-pinout-gpios/#built-in-led
    id: led

# interval:
#   - interval: 1000ms
#     then:
#       - output.turn_on: led
#       - delay: 500ms
#       - output.turn_off: led

binary_sensor:
  - platform: gpio
    pin:
      number: 27
      # https://esphome.io/components/binary_sensor/gpio#activating-internal-pullups
      mode:
        input: true
        pullup: true
    on_state:
      if:
        condition:
          binary_sensor.is_on: garage_door_opening
        then:
          output.turn_on: led
        else:
          output.turn_off: led
    device_class: opening
    name: Garage door opening
    id: garage_door_opening
    