substitutions:
  esphome_node_name: pico-w-1
  esphome_node_friendly_name: Pico W 1

packages:
  device_base: !include packages/core/device-base.yaml
  wifi: !include packages/core/wifi.yaml

rp2040:
  board: rpipicow

light:
  - platform: status_led
    name: LED
    pin: 32 # https://randomnerdtutorials.com/raspberry-pi-pico-w-pinout-gpios/#built-in-led

binary_sensor:
  - platform: gpio
    pin:
      number: 27
      # https://esphome.io/components/binary_sensor/gpio#activating-internal-pullups
      mode:
        input: true
        pullup: true
    device_class: opening
    name: Sliding gate opening
    id: sliding_gate_opening

  - platform: gpio
    pin:
      number: 18
      # https://esphome.io/components/binary_sensor/gpio#activating-internal-pullups
      mode:
        input: true
        pullup: true
    device_class: opening
    name: Garage door opening
    id: garage_door_opening
    