esphome:
  name: pico-w-1
  friendly_name: Pico W 1

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "o7GH7eTZLB9WVn4Y+uc1APScUiJaXaLyBXQ5hwd5XbI="

ota:
  password: "d7523ecc485afb775a8298543b9c8ed1"
  platform: "esphome"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Pico-W-1 Fallback Hotspot"
    password: "jIsIqVokFA1a"

light:
  - platform: status_led
    name: LED
    pin: 32 # https://randomnerdtutorials.com/raspberry-pi-pico-w-pinout-gpios/#built-in-led

binary_sensor:
  - platform: gpio
    pin:
      number: 27
      # https://esphome.io/components/binary_sensor/gpio#activating-internal-pullups
      mode:
        input: true
        pullup: true
    device_class: opening
    name: Sliding gate opening
    id: sliding_gate_opening

  - platform: gpio
    pin:
      number: 18
      # https://esphome.io/components/binary_sensor/gpio#activating-internal-pullups
      mode:
        input: true
        pullup: true
    device_class: opening
    name: Garage door opening
    id: garage_door_opening
    