esphome:
  name: ${esphome_node_name}
  friendly_name: ${esphome_node_friendly_name}

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password